MyGarage.Web/Areas/Admin/Controllers/VehicleController.cs
namespace MyGarage.Web.Areas.Admin.Controllers
{

    using Microsoft.AspNetCore.Mvc;

    using MyGarage.Services.Data.Interfaces;
    using ViewModels.Vehicle;

    using static Common.NotificationsMessagesConstants;



    public class VehicleController : BaseAdminController
    {
        private readonly ICustomerService _customerService;
        private readonly IVehicleService _vehicleService;

        public VehicleController(IVehicleService service, ICustomerService customerService)
        {
            _vehicleService = service;
            _customerService = customerService;
            
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            IEnumerable<VehicleViewModel> viewModel =
                await this._vehicleService.AllVehiclesAsync();

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            bool vehicleExist = await _vehicleService.ExistingByIdAsync(id);

            if (!vehicleExist)
            {
                this.TempData[ErrorMessage] = "Vehicle with provided id does not exist!";
                return this.RedirectToAction("All", "Vehicle");
            }

            VehicleDetailsViewModel? viewModel = 
                await this._vehicleService.ViewVehicleDetailsByIdAsync(id);

            

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            AddVehicleViewModel formModel = new AddVehicleViewModel();
            formModel.Owner = await _customerService.AllCustomersForSelectFormModelAsync();

            return View(formModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddVehicleViewModel addVehicle)
        {
            bool notActive = await _vehicleService.IsVehicleSoftDeletedAsync(addVehicle.Vin);

            if (notActive)
            {
                this.TempData[SuccessMessage] = "Vehicle was added successfully!";
                return RedirectToAction("All", "Vehicle");
            }
            if (notActive == false && !ModelState.IsValid)
            {
                
                await _vehicleService.AddVehicleAsync(addVehicle);
                this.TempData[SuccessMessage] = "Vehicle was added successfully!";
                return RedirectToAction("All", "Vehicle");
            }
            else
            {
                addVehicle.Owner = await _customerService.AllCustomersForSelectFormModelAsync();
            }

            return View(addVehicle);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, AddVehicleViewModel formModel)
        {
            bool vehicleExist = await _vehicleService.ExistingByIdAsync(id);

            if (!vehicleExist)
            {
                this.TempData[ErrorMessage] = "Vehicle with provided id does not exist!";
                return this.RedirectToAction("All", "Vehicle");
            }

            try
            {
                await this._vehicleService.EditVehicleByIdAndFormModelAsync(id, formModel);
                this.TempData[SuccessMessage] = "Vehicle edited successfully!";
            }
            catch (Exception )
            {
                this.ModelState.AddModelError(string.Empty, "Unexpected error occur while trying to update vehicle details, please try again later or contact support!");
                return View(formModel);
            }

            return RedirectToAction("Details", "Vehicle", new{id});
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            bool vehicleExist = await _vehicleService.ExistingByIdAsync(id);

            if (!vehicleExist)
            {
                this.TempData[ErrorMessage] = "Vehicle with provided id does not exist!";
                return this.RedirectToAction("All", "Vehicle");
            }

            AddVehicleViewModel formModel = await this._vehicleService.GetVehicleForEditByIdAsync(id);

            return this.View(formModel);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var vehicle = await _vehicleService.GetVehicleByIdAsync(id);
            if (vehicle == null)
            {
                this.TempData[ErrorMessage] = "Vehicle with provided id does not exist!";
                return this.RedirectToAction("All", "Vehicle"); 
            }

            return View(vehicle);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id, AddVehicleViewModel vehicleDeleteView)
        {
            Guid vehicleId = Guid.Parse(id);
            var vehicleToRemoveOwner = await _vehicleService.GetVehicleToRemoveOwnerByIdAsync(id);
            bool isOwnerRemoved = await _vehicleService.RemoveOwnerFromVehicleByIdAsync(vehicleToRemoveOwner);
            var isDeleted = await _vehicleService.SoftDeleteVehicleAsync(vehicleId);
            if (!isDeleted)
            {
                this.TempData[ErrorMessage] = "Vehicle with provided id does not exist!";
                return this.RedirectToAction("All", "Vehicle");
            }

            if (isOwnerRemoved == false)
            {
                this.TempData[ErrorMessage] = "Something went wrong while trying to remove owner from vehicle!";
                return this.RedirectToAction("All", "Vehicle");
            }
            
            this.TempData[SuccessMessage] = "Vehicle successfully deleted!";
            return RedirectToAction("All", "Vehicle");
        }

        [HttpGet]
        public async Task<IActionResult> AddOwner(string id)
        {
            AddVehicleViewModel formModel = await this._vehicleService.GetVehicleForEditByIdAsync(id);
 
            return View(formModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddOwner(string id, AddVehicleViewModel vehicleViewModel)
        {
            var vehicle = await _vehicleService.GetVehicleByIdAsync(id);

            if (vehicle == null)
            {
                TempData[ErrorMessage] = "No Vehicle with Provided Id!";
            }

            await _vehicleService.AddOwnerToVehicleByIdAsync(vehicle!.Id, vehicleViewModel);
            TempData[SuccessMessage] = "Successfully added owner to vehicle!";
            return RedirectToAction("Details", "Vehicle", new{vehicle.Id});
        }

        [HttpGet]
        public async Task<IActionResult> RemoveOwner(string id)
        {

            var vehicle = await _vehicleService.GetVehicleToRemoveOwnerByIdAsync(id);
            if (vehicle == null)
            {
                TempData[ErrorMessage] = "Vehicle with provided Id do not exist!";
                return RedirectToAction("All", "Vehicle");
            }

            return View(vehicle);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveOwner(RemoveOwnerFormModel vehicle, string id)
        {
            var isOwnerDeleted = await _vehicleService.RemoveOwnerFromVehicleByIdAsync(vehicle);

            if (isOwnerDeleted)
            {
                TempData[SuccessMessage] = "Vehicle owner have been removed from vehicle!";
                return this.RedirectToAction("Details", "Vehicle", new{vehicle.Id});
            }

            TempData[ErrorMessage] = "Something went wrong please try again later or contact support!";
            return this.RedirectToAction("All", "Vehicle");
        }
    }
}

MyGarage.Web/Controllers/JobCardController.cs
namespace MyGarage.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using MyGarage.Services.Data.Interfaces;
    using static Common.NotificationsMessagesConstants;

    public class JobCardController : Controller
    {

        private readonly IJobCardService _jobCardService;

        public JobCardController( IJobCardService jobCardService)
        {

            _jobCardService = jobCardService;

        }


        public async Task<IActionResult> Details(string id)
        {
            var model = await _jobCardService.GetJobCardForDetailsViewAsync(id);

            if (model == null)
            {
                TempData[ErrorMessage] =
                    "Something went wrong while trying to get your job card details! Please try again later or contact administrator.";
                return RedirectToAction("All", "Vehicle");
            }

            return View(model);
        }

    }
}

MyGarage.Web/Controllers/VehicleController.cs
namespace MyGarage.Web.Controllers
{
    using Infrastructure.Extensions;
    using MyGarage.Services.Data.Interfaces;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels.Vehicle;
    using static Common.NotificationsMessagesConstants;



    [Authorize]
    public class VehicleController : Controller
    {

        private readonly IVehicleService _vehicleService;

        public VehicleController(IVehicleService service)
        {
            _vehicleService = service;

            
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            IEnumerable<VehicleViewModel> viewModel =
                await this._vehicleService.AllVehiclesByUserIdAsync(this.User.GetUserId()!);

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            bool vehicleExist = await _vehicleService.ExistingByIdAsync(id);

            if (!vehicleExist)
            {
                this.TempData[ErrorMessage] = "Vehicle with provided id does not exist!";
                return this.RedirectToAction("All", "Vehicle");
            }

            VehicleDetailsViewModel? viewModel = 
                await this._vehicleService.ViewVehicleDetailsByIdAsync(id);

            

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var vehicle = await _vehicleService.GetVehicleByIdAsync(id);
            if (vehicle == null)
            {
                this.TempData[ErrorMessage] = "Vehicle with provided id does not exist!";
                return this.RedirectToAction("All", "Vehicle"); 
            }

            return View(vehicle);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id, VehicleDeleteViewModel vehicleDeleteView)
        {
            Guid vehicleId = Guid.Parse(id);
            var vehicle = await _vehicleService.GetVehicleToRemoveOwnerByIdAsync(id);
            var isOwnerRemoved = await _vehicleService.RemoveOwnerFromVehicleByIdAsync(vehicle);
            var isDeleted = await _vehicleService.SoftDeleteVehicleAsync(vehicleId);
            if (!isDeleted)
            {
                this.TempData[ErrorMessage] = "Vehicle with provided id does not exist!";
                return this.RedirectToAction("All", "Vehicle");
            }
            if (isOwnerRemoved == false)
            {
                this.TempData[ErrorMessage] = "Something went wrong while trying to delete your vehicle, please try again later or contact administrator!";
                return this.RedirectToAction("All", "Vehicle");
            }

            
            this.TempData[SuccessMessage] = "Vehicle successfully deleted!";
            return RedirectToAction("All", "Vehicle");
        }

    }
}

MyGarage.Web/Areas/Admin/Views/Vehicle/Add.cshtml
@model AddVehicleViewModel

@{
    ViewData["Title"] = "Add New Vehicle";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />


<partial name="_VehicleFormPartial" model="@Model"/>

@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

MyGarage.Web/Areas/Admin/Views/Vehicle/AddOwner.cshtml
@model AddVehicleViewModel

@{
    ViewData["Title"] = "Add owner";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr/>

<partial name="_VehicleFormPartial" model="@Model" />

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

MyGarage.Web/Areas/Admin/Views/Vehicle/All.cshtml
@model IEnumerable<VehicleViewModel>

@{
    ViewData["Title"] = "All Vehicles!";
    var vehicles = Model.ToList();
    var count = 1;
}

<div class="text-centre mb-5" align="center">
    <h2 class="display-4 text-centre">@ViewData["Title"]</h2>
</div>
<hr/>
<div align="center" class="mb-5">
    <a type="button" class="btn btn-primary" asp-area="Admin" asp-controller="Vehicle" asp-action="Add">Add Vehicle</a>
</div>

<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Make</th>
                <th scope="col">Model</th>
                <th scope="col">Registration Plate</th>
                <th scope="col">VIN</th>
                <th scope="col">Year</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>

            </tr>
        </thead>
        <tbody>
        @if (vehicles.Count == 0)
        {
            <h3>There is no vehicles added!</h3>
        }
        else
        {
            @foreach (var vehicle in vehicles)
            {

                <tr>
                    <th scope="row">@count</th>
                    <td>@vehicle.Make</td>
                    <td>@vehicle.Model</td>
                    <td>@vehicle.RegistrationNumber</td>
                    <td>@vehicle.Vin</td>
                    <td>@vehicle.YearManufactured</td>
                    <td><a type="button" class="btn btn-success" asp-area="Admin" asp-controller="JobCard" asp-action="Create" asp-route-id="@vehicle.Id">Create Job Card</a></td>
                    <td><a type="button" class="btn btn-primary" asp-area="Admin" asp-controller="Vehicle" asp-action="Details" asp-route-id="@vehicle.Id">View Details And ServiceHistory</a></td>
                    <td><a type="button" class="btn btn-warning" asp-area="Admin" asp-controller="Vehicle" asp-action="Edit" asp-route-id="@vehicle.Id">Edit</a></td>
                    <td>@if (Model != null)
                        {
                            <a type="button" class="btn btn-danger" asp-area="Admin" asp-controller="Vehicle" asp-action="Delete" asp-route-id="@vehicle.Id">Delete</a>
                        }</td>
                </tr>

                count++;
            }
        }
        </tbody>
    </table>
</div>

MyGarage.Web/Areas/Admin/Views/Vehicle/Delete.cshtml
@model VehicleDeleteViewModel
@{
    ViewData["Title"] = "Delete Vehicle";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<form method="post" asp-area="Admin" asp-action="Delete">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control" disabled="disabled" />
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" disabled="disabled" />
            </div>
            <div class="form-group">
                <label asp-for="Vin" class="control-label"></label>
                <input asp-for="Vin" class="form-control" disabled="disabled" />
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </div>
</form>

MyGarage.Web/Areas/Admin/Views/Vehicle/Details.cshtml
@model VehicleDetailsViewModel


@{
    ViewData["Title"] = "Vehicle Details";
    var jobCards = Model.JobCards!.ToList();
}


<head>
    <title>@ViewData["Title"]</title>
</head>
<form asp-area="Admin" asp-action="Details">
    <div asp-area="" class="container mt-4">
        <h1>Vehicle Details</h1>
        <a type="button" class="btn btn-warning" asp-area="Admin" asp-controller="Vehicle" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        <a type="button" class="btn btn-danger" asp-area="Admin" asp-controller="Vehicle" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
        <hr />

        <div class="row">
            <div class="col-md-4">
                <h4>Make:</h4>
            </div>
            <div class="col-md-8">
                <p>@Model.Make</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h4>Model:</h4>
            </div>
            <div class="col-md-8">
                <p>@Model.Model</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h4>VIN:</h4>
            </div>
            <div class="col-md-8">
                <p>@Model.Vin</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h4>Engine Number:</h4>
            </div>
            <div class="col-md-8">
                <p>@Model.EngineNumber</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h4>Registration Number:</h4>
            </div>
            <div class="col-md-8">
                <p>@Model.RegistrationNumber</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h4>Year Manufactured:</h4>
            </div>
            <div class="col-md-8">
                <p>@Model.YearManufactured</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h4>Fuel Type:</h4>
            </div>
            <div class="col-md-8">
                <p>@Model.FuelType</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h4>Mileage:</h4>
            </div>
            <div class="col-md-8">
                <p>@Model.Mileage</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h4>Vehicle Owner:</h4>
            </div>
            @if (Model.VehicleOwner?.Id == null
            || Model.VehicleOwner.Id == Guid.Empty.ToString()
            || string.IsNullOrEmpty(Model.VehicleOwner.Id))
            {
                <div class="col-md-8">
                    <h4>This vehicle do not have an owner!</h4>
                </div>

                <a type="button" class="btn btn-primary" asp-area="Admin" asp-controller="Vehicle" asp-action="AddOwner" asp-route-id="@Model.Id">Add Owner</a>
            }
            else
            {
                <div class="col-md-8">
                    <p>Name: @Model.VehicleOwner.Name</p>
                    <p>Phone: @Model.VehicleOwner.PhoneNumber</p>
                    <p>Email: @Model.VehicleOwner.Email</p>
                </div>
                <a type="button" class="btn btn-warning" asp-area="Admin" asp-controller="Vehicle" asp-action="RemoveOwner" asp-route-id="@Model.Id">Remove owner!</a>
            }

        </div>
        <hr />
        <div class="row">

            @if (@jobCards.Count == 0)
            {
                <h3 class="text-center mt-4">There is no jobs done on this vehicle yet!</h3>
            }
            else
            {
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="text-center" scope="col">Date Added</th>
                            <th class="text-center" scope="col">Mileage</th>
                            <th class="text-center" scope="col">Mechanic Name</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var jobCard in @jobCards)
                        {

                            <tr>
                                <td class="text-center">@jobCard.CreatedOn</td>
                                <td class="text-center">@jobCard.Mileage</td>
                                <td class="text-center">@jobCard.Mechanic.Name @jobCard.Mechanic.LastName</td>

                                <td class="text-end"><a type="button" class="btn btn-primary" asp-area="Admin" asp-controller="JobCard" asp-action="Details" asp-route-id="@jobCard.Id">View Details</a></td>
                                <td class="text-center"><a type="button" class="btn btn-warning" asp-area="Admin" asp-controller="JobCard" asp-action="Edit" asp-route-id="@jobCard.Id">Edit card</a></td>
                                <td><a type="button" class="btn btn-danger" asp-area="Admin" asp-controller="JobCard" asp-action="Delete" asp-route-id="@jobCard.Id">Delete</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            }

        </div>
    </div>

</form>

MyGarage.Web/Areas/Admin/Views/Vehicle/Edit.cshtml
@model AddVehicleViewModel

@{
    ViewData["Title"] = "Edit Vehicle";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr/>

<partial name="_VehicleFormPartial" model="@Model" />

@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
}

MyGarage.Web/Areas/Admin/Views/Vehicle/RemoveOwner.cshtml
@model RemoveOwnerFormModel
@{
    ViewData["Title"] = "Remove Owner from vehicle!";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<form method="post" asp-area="Admin" asp-action="RemoveOwner" asp-route-id="@Model.Id">
    <div class="row">
        <div class="col-md-8 mb-3">
            <div class="form-group">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control" disabled="disabled" />
            </div>
            <div class="form-group mb-3">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" disabled="disabled" />
            </div>
            <div class="form-group mb-3">
                <label asp-for="Vin" class="control-label">VIN</label>
                <input asp-for="Vin" class="form-control" disabled="disabled" />
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Remove owner" class="btn btn-danger" />
            </div>
        </div>
    </div>
</form>